spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/bulletin
    username: postgres
    password: NOVIANTO
  data:
    web:
      pageable:
        one-indexed-parameters: true
    redis:
      host: localhost
      port: 6379
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 50MB
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  security:
    jwt:
      token:
        access-expiration-time: 3600000
        refresh-expiration-time: 86400000
        secret: c8d7c086fe64a415ee1fafe90b1a663ef635f903b129d2bd752af401c817bee0
    oauth2:
      google-revoke-uri: https://oauth2.googleapis.com/revoke
      client:
        registration:
          google:
            client-id: <YOUR_GOOGLE_CLIENT_ID>
            client-secret: <YOUR_GOOGLE_CLIENT_SECRET>
            scope: profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-authentication-method: post
            authorization-grant-type: authorization_code
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://openidconnect.googleapis.com/v1/userinfo
            user-name-attribute: sub

logging:
  level:
    root: INFO
    org:
      springframework:
        web: DEBUG
        security: DEBUG

user:
  profile:
    image:
      store-directory: src/main/resources/static/store/user-profile
      default-directory: src/main/resources/static/user-profile

post:
  file:
    store-directory: src/main/resources/static/store